// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace JSONMigrationDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240103115329_Renamed Name property, added NewProperty, removed Description")]
    partial class RenamedNamepropertyaddedNewPropertyremovedDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Repository.Models.RegularTableClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ExampleTypeCollection")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<double>("TestColumn")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("LogData");
                });
#pragma warning restore 612, 618
        }
    }
}
